### ISSUE TITLE
Implement fulltext search function for an array of objects

### ISSUE THREAD

**Issue by jamescoq** [tommmyy/ramda-extension#122]
it would be nice to have a fulltext search function that is able to search according to given string value in the array of objects values. 

And it would be even nicer if that search function could search through an array of deeply nested objects.

**Example:**
input array:
[
  {
    "id": 1,
    "name": "Exposure time",
    "description": "Possible exposure times",
    "type": "text",
    "language": "en",
    "attributes": {
        "min": "1/1000 sec",
        "max": "30 sec"
    },
  },
  {
    "id": 2,
    "name": "Durability",
    "description": "Durable material",
    "type": "text",
    "language": "en"
  },
  {
    "id": 3,
    "name": "Stabilizer",
    "description": "Stabilizer enabled",
    "type": "boolean",
    "language": "en"
  }
]

search string: "sec"
result: 
[
  {
    "id": 1,
    "name": "Exposure time",
    "description": "Possible exposure times",
    "type": "text",
    "language": "en",
    "attributes": {
        "min": "1/1000 sec",
        "max": "30 sec"
    },
  }
]

**Comment by aizerin** [comment]
It looks like a challenge, I will take it :).

**Comment by tommmyy** [comment]
@aizerin Yes, it is.. especially if the function will work even for nested properties and values.
