### ISSUE TITLE
Update to Ramda 0.26

### ISSUE THREAD

**Issue by tommmyy** [tommmyy/ramda-extension#128]
-  rename `R_.includes` to `R_.flipIncludes`
- replace `R.merge` with `R.mergeRight`
- use `R.thunkify` instead of our implementation

**Comment by jbradle** [comment]
flipIncludes? Should it be flipContains?

I think that includes is good name :-) What is reason to rename this function. We use it everywhere.

**Comment by tommmyy** [comment]
@jbradle See https://github.com/ramda/ramda/pull/2452

**Comment by jbradle** [comment]
oh, i didn't know
