### ISSUE TITLE
Negate function

### ISSUE THREAD

**Issue by jeswr** [tommmyy/ramda-extension#179]
**Describe the solution you'd like**
A function that `negate`s another function. If `f(...p) = true` then `negate(f)(...p) = false` and vice versa.

**Additionally propose a solution**
Function that negates a function that returns boolean values

Type Signature
`((...p) -> Bool) -> ((...p) -> Bool)`

Possible implementation
`const negate = f => R.compose(R.not, f)`

Example use cases
```
const notIn = negate(R.has)
```

**Comment by jbradle** [comment]
Looks like [complement](https://ramdajs.com/docs/#complement) from ramda library.
