### ISSUE TITLE
toUpperFirst is throwing an exception

### ISSUE THREAD

**Issue by jamescoq** [tommmyy/ramda-extension#183]
**Describe the bug**
a function `toUpperFirst` is throwing an exception when passed a null or undefined or empty string value

**To Reproduce**
R_.toUpperFirst('');
R_.toUpperFirst(null);
R_.toUpperFirst(undefined);

**Expected behavior**
A function should return null or undefined or empty string value.

**Comment by tommmyy** [comment]
Closed by #190
