### ISSUE TITLE
new function: padLeftUntil, padRightUntil

### ISSUE THREAD

**Issue by tommmyy** [tommmyy/ramda-extension#61]
http://ramdajs.com/repl/?v=0.25.0#?const%20padLeftUntil%20%3D%20useWith%28until%2C%20%5Bidentity%2C%20concat%2C%20toString%5D%29%3B%0Aconst%20myPad%20%3D%20padLeftUntil%28x%20%3D%3E%20x.length%20%3E%2010%2C%20%270%27%29%20%0A%0AmyPad%28111%29%3B

Do you think it is useful? @jbradle @aizerin @lukasduspiva @wafflepie @neerajdotname

**Comment by aizerin** [comment]
👍

**Comment by lukasduspiva** [comment]
Yes, I think you should sometimes need this function.

**Comment by jbradle** [comment]
Go for it
