### ISSUE TITLE
cx function leaves strings with spaces

### ISSUE THREAD

**Issue by ondrejkralik** [tommmyy/ramda-extension#77]
Hello,

we use `cx` as a replacement of `classNames` lib.

But unfortunatelly it produces final classnames with more spaces than necessary.
For example:
```
R_.cx(['Table', 'MagicTable '])    // "Table MagicTable "
R_.cx(['Table', '    MagicTable']) // "Table     MagicTable"
R_.cx([' Table', 'MagicTable'])    // " Table MagicTable"
```

It would be nice if `cx` remove unnecessary spaces, isn't it?

**Comment by tommmyy** [comment]
@ondrejkralik Thank you for the issue. We will look at it. Or do you want to help?

**Comment by ondrejkralik** [comment]
I'm sorry, for confusing you. `classnames` does NOT trim too.
But it would be nice if `cx` did :) although you need to consider the performance of this method.

And I'm not sure if I am good enough to help with hardcore ramda.
