### ISSUE TITLE
alwaysEmptyObject and alwaysEmptyArray do not always return empty array or object

### ISSUE THREAD

**Issue by nfantone** [tommmyy/ramda-extension#97]
Output from `alwaysEmptyArray` and `alwaysEmptyObject` cannot be trusted to be always empty. Specially if their outputs are being passed around as inputs to third party libraries. This can lead to hard to track bugs and odd behaviors.

```js
R_.alwaysEmptyArray(); // []
R_.alwaysEmptyArray().push(42); 
R_.alwaysEmptyArray(); // [42] <- return value has been changed forever for every other subsequent call
```

I propose we either: 

- _Change the name of the functions_ to reflect the above fact.
- Return a `R.clone` of the `emptyArray` or `emptyObject` each time:

```js
const alwaysEmptyArray = () => clone(emptyArray);
```

- Leverage the new (unreleased as of yet) [`R.thunkify`](https://github.com/ramda/ramda/pull/2551) function to create a point-free reusable factory of clones and implement other `always*` functions based off of it.

```js
const alwaysNew = thunkify(clone);
const alwaysEmptyArray = alwaysNew(emptyArray);
```

> DISCLAIMER: I was the author of the `thunkify` PR.

**Comment by tommmyy** [comment]
...although we must wait for Ramda release which will contain `thunkify`.

**Comment by tommmyy** [comment]
@nfantone ok, agreed. You can temporarily add thunkfify function. Thank you!

**Comment by nfantone** [comment]
@tommmyy I was trying to get a PR together for this today and found out that I cannot install the project on a fresh clone (running on macOS, `node` `v10.4.1 and `npm` `6.1.0`).

The installation for `fsevents` seems to fail. It tries to download binaries, errors and defaults to compile from source which also fails.

```sh
❯ git clone git@github.com:nfantone/ramda-extension.git
❯ cd ramda-extension
❯ npm i

> fsevents@1.1.3 install /Users/nfantone/Development/js/ramda-extension/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.4.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)

[...bunch more...]

make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12
gyp ERR! System Darwin 17.6.0

[...even more...]
```

Removing `package-lock.json` solved the issue for me. Incidentally, I found out that it _does work_ with `yarn` out of the box. I'm guessing one of the lockfiles is not up-to-date?

**Comment by tommmyy** [comment]
@nfantone yes, you are correct! It is our bad, that we kept `package-lock.json`. I am gonna to remove it. I added [issue](https://github.com/tommmyy/ramda-extension/issues/100) for that.
